version: '3.8'

services:
  web:
    network_mode: host
    env_file:
      - ./.env
    command: uvicorn main:app --host 0.0.0.0 --reload --port 5000 --log-level debug
    volumes:
      - ./:/app
    ports:
      - 5000:5000