kind: Service
apiVersion: v1
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    app: server
  ports:
    - name: http
      protocol: TCP
      port: 8000
      targetPort: 8000
---
kind: Service
apiVersion: v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  type: NodePort
  selector:
    app: nginx
  ports:
    - name: nginx
      port: 80
      targetPort: 80